[tool.poetry]
name = "dev-template"
authors = ["Stephen Price <stephen@stp5.net>"]
version = "0.1.0"
description = ""

[tool.poetry.dependencies]
python = "^3.8"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
